import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

import inspect
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.data import load_dataset  # noqa: E402
from src.train import fit  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
FIG, RES = ROOT / "figures", ROOT / "results"
BLUE, ORANGE, GREY = "#1f5fa8", "#d0612a", "#555555"
METRICS = ["accuracy", "precision", "specificity", "sensitivity", "roc_auc", "pr_auc"]
LABELS = ["Accuracy", "Precision", "Specificity", "Sensitivity", "ROC AUC", "PR AUC"]


def load(name):
    p = RES / name
    return json.loads(p.read_text()) if p.exists() else None


def new_slide(title, n):
    fig = plt.figure(figsize=(13.33, 7.5))
    fig.patches.append(plt.Rectangle((0, 0.88), 1, 0.12, transform=fig.transFigure, color=BLUE))
    fig.text(0.04, 0.94, title, color="white", fontsize=28, weight="bold", va="center")
    fig.text(0.96, 0.03, str(n), color=GREY, fontsize=12, ha="right")
    fig.text(0.04, 0.03, "HIKNet review | Guru R Bharadwaj", color=GREY, fontsize=12)
    return fig


def bullets(fig, items, x=0.05, y=0.80, w=None, size=18, gap=0.075):
    for item in items:
        sub = item.startswith("-")
        fig.text(x + (0.03 if sub else 0), y, ("–  " if sub else "•  ") + item.lstrip("- "),
                 fontsize=size - (2 if sub else 0), va="top", color="black" if not sub else GREY, wrap=True)
        y -= gap * (0.85 if sub else 1)


def image(fig, name, rect):
    ax = fig.add_axes(rect)
    ax.imshow(mpimg.imread(FIG / name))
    ax.axis("off")


def table(fig, rect, cols, rows, size=16):
    ax = fig.add_axes(rect)
    ax.axis("off")
    t = ax.table(cellText=rows, colLabels=cols, loc="center", cellLoc="center")
    t.auto_set_font_size(False)
    t.set_fontsize(size)
    t.scale(1, 2.0)
    for (r, c), cell in t.get_celld().items():
        cell.set_edgecolor("#cccccc")
        if r == 0:
            cell.set_facecolor(BLUE)
            cell.set_text_props(color="white", weight="bold")
    return t


def box(ax, x, y, w, h, text, color):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.01", fc=color, ec=BLUE, lw=1.5))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=14)


def arrow(ax, x0, x1, y):
    ax.add_patch(FancyArrowPatch((x0, y), (x1, y), arrowstyle="-|>", mutation_scale=20, color=GREY, lw=1.5))


def fmt(m):
    return [f"{m[k]:.3f}" for k in METRICS]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=ROOT / "docs" / "slides.pdf")
    parser.add_argument("--png-dir", help="also save each slide as PNG (for previewing)")
    args = parser.parse_args()
    out = Path(args.out)
    out.parent.mkdir(exist_ok=True)

    svm = load("svm_metrics.json")
    sel = load("selected_features.json")
    head = load("tune_head.json")
    hp = load("tune_hparams.json")
    final = load("final_comparison.json")
    comp = load("model_comparison.json")
    _, y = load_dataset()
    n_all, n_pos = len(y), int(sum(y))
    fd = {k: v.default for k, v in inspect.signature(fit).parameters.items()}
    n_test = sum(svm["test"][k] for k in ["tp", "fp", "tn", "fn"])
    best_k = max(hp["sweeps"]["kernel"], key=lambda e: e["accuracy"]["mean"])["value"]
    folds = len(next(iter(comp.values()))["folds"]) if comp else 0
    slides = []

    # 1 title
    fig = plt.figure(figsize=(13.33, 7.5))
    fig.patches.append(plt.Rectangle((0, 0), 1, 1, transform=fig.transFigure, color=BLUE))
    fig.text(0.5, 0.62, "HIKNet in PyTorch", color="white", fontsize=44, weight="bold", ha="center")
    fig.text(0.5, 0.50, "Classifying head impacts vs false positives from instrumented mouthguards",
             color="white", fontsize=22, ha="center")
    fig.text(0.5, 0.30, "Guru R Bharadwaj  (PES1UG24CS177)", color="white", fontsize=20, ha="center")
    slides.append(fig)

    # 2 problem
    fig = new_slide("Problem", 2)
    bullets(fig, [
        "Instrumented mouthguards record head kinematics to study head impacts",
        "Many recorded events are false positives (chewing, talking, dropping the guard)",
        "Goal: binary classifier - real head impact vs false positive",
        "Input: 6 channels (linear + angular acceleration x/y/z), 199 samples at 1000 Hz",
        "Compare a feature-based SVM baseline with HIKNet, a 1D/2D CNN on raw signals",
    ])
    slides.append(fig)

    # 3 data
    fig = new_slide("Data", 3)
    bullets(fig, [
        f"Synthetic mock dataset: {n_all} samples ({n_pos} impacts / {n_all - n_pos} false positives)",
        "Generated by scripts/make_mock_data.py - the real lab data was unavailable",
        "Same shape as the original: 6 channels x 199 timesteps @ 1000 Hz",
        "Signals standardized; stratified 70/30 train/eval split (seed 0)",
        "Results validate the pipeline only - they are NOT real-world performance",
    ])
    fig.text(0.5, 0.25, "All numbers in this deck come from synthetic data.", ha="center",
             fontsize=20, weight="bold", color=ORANGE)
    slides.append(fig)

    # 4 EDA
    fig = new_slide("Exploratory data analysis", 4)
    image(fig, "time_domain.png", [0.02, 0.10, 0.47, 0.75])
    image(fig, "freq_domain.png", [0.51, 0.10, 0.47, 0.75])
    slides.append(fig)

    # 5 SVM
    fig = new_slide("SVM baseline", 5)
    bullets(fig, [
        "Hand-crafted features: PSD bands, wavelet (WT) bands, biomechanical model terms",
        f"Greedy forward selection by CV ROC AUC -> {len(sel['names'])} features",
    ], size=17)
    rows = [[i + 1, n, f"{a:.3f}"] for i, (n, a) in enumerate(zip(sel["names"], sel["cv_auc"]))]
    t = table(fig, [0.04, 0.08, 0.46, 0.58], ["#", "Selected feature", "CV AUC"], rows, size=13)
    t.scale(1, 0.75)
    table(fig, [0.54, 0.25, 0.42, 0.40], ["Metric", "CV", f"Test ({n_test})"],
          [[l, f"{svm['cv'][k]:.3f}", f"{svm['test'][k]:.3f}"] for k, l in zip(METRICS, LABELS)], size=15)
    slides.append(fig)

    # 6 architecture
    fig = new_slide("HIKNet architecture", 6)
    ax = fig.add_axes([0.02, 0.30, 0.96, 0.52])
    ax.set(xlim=(0, 10), ylim=(0, 3))
    ax.axis("off")
    blocks = [("Input\n6 x 199", "#eeeeee"),
              ("Conv1d 150\nk=15, ReLU\nMaxPool 2\nDropout 0.4", "#dbe7f5"),
              ("Conv1d 150\nk=15, ReLU\nMaxPool 2\nDropout 0.4", "#dbe7f5"),
              ("Reshape to\n1-channel\n2D map", "#eeeeee"),
              ("Conv2d 150\n(3,15)\nstride (3,1)\nReLU", "#fbe3d6"),
              ("Global\navg pool", "#fbe3d6"), ("Linear\n-> logit", "#fbe3d6")]
    w, step = 1.15, 1.40
    for i, (txt, c) in enumerate(blocks):
        box(ax, 0.1 + i * step, 0.9, w, 1.4, txt, c)
        if i:
            arrow(ax, 0.1 + (i - 1) * step + w + 0.02, 0.1 + i * step - 0.02, 1.6)
    bullets(fig, [
        "Two Conv1d blocks learn temporal filters; Conv2d then scans the (time x filter) map",
        "GAP head keeps parameters low; sigmoid on the logit gives P(impact)",
    ], y=0.30, size=17)
    slides.append(fig)

    # 7 training
    fig = new_slide("Training", 7)
    bullets(fig, [
        f"Optimizer: Adam, learning rate {fd['lr']:g}, batch size {fd['batch_size']}",
        "Loss: binary cross-entropy on the logit (BCEWithLogits)",
        f"Early stopping on validation loss, patience {fd['patience']}; best checkpoint restored",
        f"Final run stopped at best epoch {final['HIKNet']['best_epoch']}",
        f"Tuning: each config repeated {hp['repeats']}x with different seeds, {hp['epochs']} epochs max",
    ])
    slides.append(fig)

    # 8 CV comparison
    fig = new_slide(f"RecursiveNet vs HIKNet: {folds}-fold CV", 8)
    if comp:
        names = {"recursivenet": "RecursiveNet", "hiknet": "HIKNet"}
        table(fig, [0.04, 0.40, 0.92, 0.35], ["Model"] + LABELS,
              [[names.get(n, n)] + fmt(comp[n]["mean"]) for n in comp], size=16)
        best = max(comp, key=lambda n: comp[n]["mean"]["roc_auc"])
        bullets(fig, [f"Same {folds} stratified folds for both models; mean over folds",
                      f"Higher mean ROC AUC: {names.get(best, best)}"], y=0.32)
    else:
        fig.text(0.5, 0.5, "results/model_comparison.json not available", ha="center", fontsize=20)
    slides.append(fig)

    # 9 tuning
    fig = new_slide("Tuning: output head and hyperparameters", 9)
    rows = [[k.upper(), f"{v['accuracy']['mean']:.3f} ± {v['accuracy']['std']:.3f}",
             f"{v['roc_auc']['mean']:.3f}"] for k, v in head["results"].items()]
    table(fig, [0.03, 0.08, 0.42, 0.28], ["Head", "Accuracy", "ROC AUC"], rows, size=15)
    b, d = hp["best"], hp["default"]
    bullets(fig, [
        f"Best head: {head['best'].upper()}",
        f"Default: {d['filters']} filters, k={d['kernel']}, dropout {d['dropout']}",
        f"Best: {b['filters']} filters, k={b['kernel']}, dropout {b['dropout']}",
        f"- best kernel by accuracy: {best_k}",
    ], x=0.52, y=0.36, size=16, gap=0.07)
    image(fig, "tuning.png", [0.03, 0.40, 0.94, 0.46])
    slides.append(fig)

    # 10 final comparison
    fig = new_slide("Final comparison: HIKNet vs SVM (eval set)", 10)
    n = len(final["y"])
    table(fig, [0.03, 0.40, 0.42, 0.40], ["Metric", "HIKNet", "SVM"],
          [[l, f"{final['HIKNet']['metrics'][k]:.3f}", f"{final['SVM']['metrics'][k]:.3f}"]
           for k, l in zip(METRICS, LABELS)], size=15)
    fig.text(0.24, 0.30, f"Same held-out split, n = {n}", ha="center", fontsize=16, color=GREY)
    image(fig, "roc_curves.png", [0.46, 0.10, 0.26, 0.75])
    image(fig, "pr_curves.png", [0.72, 0.10, 0.26, 0.75])
    slides.append(fig)

    # 11 limitations
    fig = new_slide("Limitations", 11)
    bullets(fig, [
        "Synthetic data only: no claim about real mouthguard performance",
        f"Small dataset ({n_all} events) -> wide variance across seeds and splits",
        "Single held-out split for the final comparison; no external test set",
        "SVM feature set re-selected per split, so its features differ between runs",
        "Mock generator may make the classes easier or harder than real data",
    ])
    slides.append(fig)

    # 12 conclusion
    fig = new_slide("Conclusion", 12)
    h, s = final["HIKNet"]["metrics"], final["SVM"]["metrics"]
    bullets(fig, [
        "Full PyTorch pipeline: data, SVM baseline, HIKNet, CV, tuning, evaluation",
        f"Eval split, HIKNet vs SVM: accuracy {h['accuracy']:.3f} vs {s['accuracy']:.3f}, "
        f"ROC AUC {h['roc_auc']:.3f} vs {s['roc_auc']:.3f}",
        f"Best tuned config: {head['best'].upper()} head, {b['filters']} filters, k={b['kernel']}, dropout {b['dropout']}",
        "Next step: rerun on real instrumented-mouthguard data",
    ])
    slides.append(fig)

    with PdfPages(out) as pdf:
        for i, fig in enumerate(slides, 1):
            pdf.savefig(fig)
            if args.png_dir:
                Path(args.png_dir).mkdir(parents=True, exist_ok=True)
                fig.savefig(Path(args.png_dir) / f"slide_{i:02d}.png", dpi=60)
            plt.close(fig)
    print(f"saved {out} ({len(slides)} slides)")


if __name__ == "__main__":
    main()
